---

- name: Install the required packages
  vars:
    pkgs:
      - unzip
      - modsecurity-crs
      - libapache2-mod-security2
      - apache2
  apt:
    name: '{{ pkgs }}'
    state: latest

- name: Create AppArmor profile for Apache
  register: apache_aa_profile
  notify:
    - Restart Apache
    - Restart AppArmor
  template:
    src: apparmor.d/usr.sbin.apache2
    dest: /etc/apparmor.d/usr.sbin.apache2

- name: Enfore AppArmor profile for Apache
  notify:
    - Restart Apache
    - Restart AppArmor
  when: apache_aa_profile.changed
  shell: aa-enforce usr.sbin.apache2

- name: Activate apache security module
  notify: Restart Apache
  apache2_module:
    state: present
    name: security2

- name: Use the recommended settings for mod security
  copy:
    src: /etc/modsecurity/modsecurity.conf-recommended
    dest: /etc/modsecurity/modsecurity.conf
    remote_src: true

- name: Activate mod_security
  notify: Restart Apache
  replace:
    path: /etc/modsecurity/modsecurity.conf
    regexp: '^SecRuleEngine DetectionOnly'
    replace: 'SecRuleEngine On'
  
