---

- name: Get the current timezone
  register: timezone
  shell: cat /etc/timezone

- name: Install the required packages
  tags: apt
  apt:
    name: php-fpm
    state: present

- name: Update PHP configuration
  notify: Restart php-fpm
  replace:
    path: /etc/php/7.0/fpm/php.ini
    regexp: '{{ option.regexp }}'
    replace: '{{ option.replace }}'
  with_items:
    - regexp: '^;?date.timezone\s=.*'
      replace: 'date.timezone = {{ timezone.stdout }}'
  loop_control:
    loop_var: option
