---

# Database configuration ======================================================

- name: Initialise the drupal database password parameters
  set_fact:
    db_password_path: "{{ playbook_dir }}/../../backup/{{ network.domain }}/postgresql/drupal.pwd"
    db_password_params: "chars=ascii_letters,digits length=16"

- name: Create the drupal database account password
  set_fact:
    drupal_db_password: '{{ lookup("password", db_password_path + " " + db_password_params) }}'

- name: Create the database user
  tags: postgres
  become: true
  become_user: postgres
  postgresql_user:
    name: drupal
    password: '{{ drupal_db_password }}'
    role_attr_flags: LOGIN

- name: Create the database
  register: drupaldb
  tags: postgres
  become: true
  become_user: postgres
  postgresql_db:
    encoding: utf8
    name: drupal
    owner: drupal

- name: Initialise grants
  tags: postgres
  become: true
  become_user: postgres
  postgresql_privs:
    db: drupal
    objs: ALL_IN_SCHEMA
    privs: ALL
    role: drupal
