---

- name: Install the Debian drupal package
  apt:
    name: '{{ drupal_pkgs }}'
    state: latest

- name: Initialise the database
  include_tasks: db.yml

- name: Create the directory for Drush
  file:
    path: /usr/local/lib/drush7
    state: directory

- name: Install Drush using composer
  shell: >-
    composer require drush/drush:7.x
  args:
    chdir: /usr/local/lib/drush7
    creates: /usr/local/lib/drush7/composer.json

- name: Create the symbolic link
  file:
    src: /usr/local/lib/drush7/vendor/drush/drush/drush
    dest: /usr/local/sbin/drush
    state: link

- name: Deploy apache frontend configuration
  template:
    src: '{{ file }}'
    dest: '/etc/drupal/7/sites/default/{{ file }}'
  with_items:
    - settings.php
    - dbconfig.php
    - baseurl.php
  loop_control:
    loop_var: file

- name: Initialise the drupal admin password parameters
  set_fact:
    admin_password_path: "{{ playbook_dir }}/../../backup/{{ network.domain }}/drupal/admin.pwd"
    admin_password_params: "chars=ascii_letters,digits length=16"

- name: Create the drupal admin account password
  set_fact:
    admin_password: '{{ lookup("password", admin_password_path + " " + admin_password_params) }}'

- name: Install Drupal automatically with Drush
  shell: >-
    echo y | drush site-install standard
    --locale=en-GB
    --account-name=admin
    --account-pass={{ admin_password }}
    --account-mail="admin@{{ network.domain }}"
    --site-mail="admin@{{ network.domain }}"
    --site-name="{{ drupal.site_name }}"
    --verbose
    --clean-url
    --db-url="pgsql://drupal:{{ drupal_db_password }}@localhost/drupal"
    2>&1 >/var/log/drupal-install.log
  args:
    chdir: /usr/share/drupal7/
    creates: /var/log/drupal-install.log

- name: Deploy CRS rules for Drupal
  notify: Restart Apache
  template:
    src: crs-rules-drupal.conf
    dest: /etc/modsecurity/crs/rules-drupal.conf

- name: Configure apache server to listen on a specific port
  notify: Restart Apache
  replace:
    path: /etc/apache2/ports.conf
    regexp: '^Listen 80'
    replace: 'Listen 81'

- name: Disable apache default site
  notify: Restart Apache
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Deploy apache frontend configuration
  notify: Restart Apache
  template:
    src: apache2-front.conf
    dest: '/etc/apache2/sites-available/{{ drupal.subdomain }}.{{ network.domain }}.conf'

- name: Activate apache frontend configuration
  notify: Restart Apache
  file:
    src: '/etc/apache2/sites-available/{{ drupal.subdomain }}.{{ network.domain }}.conf'
    dest: '/etc/apache2/sites-enabled/{{ drupal.subdomain }}.{{ network.domain }}.conf'
    state: link

- name: Disable apache ssl module
  notify: Restart Apache
  apache2_module:
    state: absent
    name: ssl

- name: Activate apache rewrite and security modules
  notify: Restart Apache
  apache2_module:
    state: present
    name: '{{ module }}'
  with_items:
    - security2
    - rewrite
    - rpaf
  loop_control:
    loop_var: module

- name: Deploy nginx frontend configuration
  notify: Restart Nginx
  template:
    src: nginx-front.conf
    dest: '/etc/nginx/sites-available/{{ drupal.subdomain }}.{{ network.domain }}.conf'

- name: Activate nginx frontend configuration
  notify: Restart Nginx
  file:
    src: '/etc/nginx/sites-available/{{ drupal.subdomain }}.{{ network.domain }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ drupal.subdomain }}.{{ network.domain }}.conf'
    state: link
