---

###############################################################################
# Default system settings
system_default:
  release: stretch
  login: true
  devel: false
  debug: false
  reboot_timeout: 180

###############################################################################
# Extra security values
security_default:
  auto_update: true
  app_armor: true
  ssh_disable_root_access_with_password: true
  lock_root_password: true
  alerts_email: 'admin@{{ network.domain }}'

# Standard policies
policies:
  system:
    password: 'length=16 chars=ascii_letters,digits'
    passphrase: 'length=40'

# Encryption parameters
encryption:
  systemKeyParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/encryption/system-key.pwd {{ policies.system.passphrase }}"
  backupKeyParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/encryption/backup-key.pwd {{ policies.system.passphrase }}"

