---

###############################################################################
# Domain and hostname information
network:
  domain: sample.do
  hostname: drupal.sample.do

##############################################################################
# Extra security values
security:
  auto_update: true
  app_armor: true
  mod_security:
    install: true

###############################################################################
# System related
drupal:
  subdomain: sa-check
  site_name: Welcome to Drupal

###############################################################################
# System related
system:
  release: stretch
  ssl: letsencrypt
  devel: false
  debug: true

