---

# Prepare the system
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/defaults.yml'
    - '{{ playbook_dir }}/../../config/system.yml'
  roles:
    - role: system-prepare
      tags: system-prepare

# Create the certificate for the web site if not exists
- hosts: homebox
  vars:
    defaults_loaded: true
    redirect: true
    certificate:
      type: '{{ drupal.subdomain }}'
  vars_files:
    - '{{ playbook_dir }}/../../config/defaults.yml'
    - '{{ playbook_dir }}/../../config/system.yml'
  roles:
    - role: nginx
      tags: nginx
    - role: certificates
      tags: certificates

# Install mod-security
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/defaults.yml'
    - '{{ playbook_dir }}/../../config/system.yml'
  roles:
    - role: mod-security
      tags: mod-security

# Install Drupal
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/defaults.yml'
    - '{{ playbook_dir }}/../../config/system.yml'
  roles:
    - role: drupal
      tags: drupal
