---
# This role load all the default values, and merge them with user specified values.
# This is a first version, roughly copy and paste, but will evolve to something more
# elaborated later. The final purpose is fulfilled:
# Users can specify copy partial branches of default values, and not worry
# about new version changes.


################################################################################
# Merge system defaults
- name: Combine default and user defined system settings
  run_once: true
  when: system is defined
  tags: defaults
  set_fact:
    system: '{{ system_default | combine(system, recursive=True) }}'

- name: Use default system settings
  run_once: true
  when: system is not defined
  tags: defaults
  set_fact:
    system: '{{ system_default }}'

- name: Display merged system settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: system

################################################################################
# Merge security defaults
- name: Combine default and user defined security settings
  run_once: true
  when: security is defined
  tags: defaults
  set_fact:
    security: '{{ security_default | combine(security, recursive=True) }}'

- name: Use default security settings
  run_once: true
  when: security is not defined
  tags: defaults
  set_fact:
    security: '{{ security_default }}'

- name: Display merged security settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: security

################################################################################
# Marking the default settings as loaded should increase the speed of the deployment
- name: Mark the default settings as loaded
  run_once: true
  tags: defaults
  set_fact:
    defaults_loaded: true
